#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bookkeeping.App_Code
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="bookkeeping")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttransaction(transaction instance);
    partial void Updatetransaction(transaction instance);
    partial void Deletetransaction(transaction instance);
    #endregion
		
		public DataClassesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["bookkeepingConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<transaction> transactions
		{
			get
			{
				return this.GetTable<transaction>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[transaction]")]
	public partial class transaction : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _transaction_id;
		
		private string _transaction_name;
		
		private string _transaction_description;
		
		private decimal _transaction_amount;
		
		private int _transaction_low_level;
		
		private System.Nullable<int> _transaction_payer;
		
		private System.Nullable<int> _transaction_payee;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ontransaction_idChanging(int value);
    partial void Ontransaction_idChanged();
    partial void Ontransaction_nameChanging(string value);
    partial void Ontransaction_nameChanged();
    partial void Ontransaction_descriptionChanging(string value);
    partial void Ontransaction_descriptionChanged();
    partial void Ontransaction_amountChanging(decimal value);
    partial void Ontransaction_amountChanged();
    partial void Ontransaction_low_levelChanging(int value);
    partial void Ontransaction_low_levelChanged();
    partial void Ontransaction_payerChanging(System.Nullable<int> value);
    partial void Ontransaction_payerChanged();
    partial void Ontransaction_payeeChanging(System.Nullable<int> value);
    partial void Ontransaction_payeeChanged();
    #endregion
		
		public transaction()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_transaction_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int transaction_id
		{
			get
			{
				return this._transaction_id;
			}
			set
			{
				if ((this._transaction_id != value))
				{
					this.Ontransaction_idChanging(value);
					this.SendPropertyChanging();
					this._transaction_id = value;
					this.SendPropertyChanged("transaction_id");
					this.Ontransaction_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_transaction_name", DbType="VarChar(500)")]
		public string transaction_name
		{
			get
			{
				return this._transaction_name;
			}
			set
			{
				if ((this._transaction_name != value))
				{
					this.Ontransaction_nameChanging(value);
					this.SendPropertyChanging();
					this._transaction_name = value;
					this.SendPropertyChanged("transaction_name");
					this.Ontransaction_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_transaction_description", DbType="VarChar(5000)")]
		public string transaction_description
		{
			get
			{
				return this._transaction_description;
			}
			set
			{
				if ((this._transaction_description != value))
				{
					this.Ontransaction_descriptionChanging(value);
					this.SendPropertyChanging();
					this._transaction_description = value;
					this.SendPropertyChanged("transaction_description");
					this.Ontransaction_descriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_transaction_amount", DbType="Money NOT NULL")]
		public decimal transaction_amount
		{
			get
			{
				return this._transaction_amount;
			}
			set
			{
				if ((this._transaction_amount != value))
				{
					this.Ontransaction_amountChanging(value);
					this.SendPropertyChanging();
					this._transaction_amount = value;
					this.SendPropertyChanged("transaction_amount");
					this.Ontransaction_amountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_transaction_low_level", DbType="Int NOT NULL")]
		public int transaction_low_level
		{
			get
			{
				return this._transaction_low_level;
			}
			set
			{
				if ((this._transaction_low_level != value))
				{
					this.Ontransaction_low_levelChanging(value);
					this.SendPropertyChanging();
					this._transaction_low_level = value;
					this.SendPropertyChanged("transaction_low_level");
					this.Ontransaction_low_levelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_transaction_payer", DbType="Int")]
		public System.Nullable<int> transaction_payer
		{
			get
			{
				return this._transaction_payer;
			}
			set
			{
				if ((this._transaction_payer != value))
				{
					this.Ontransaction_payerChanging(value);
					this.SendPropertyChanging();
					this._transaction_payer = value;
					this.SendPropertyChanged("transaction_payer");
					this.Ontransaction_payerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_transaction_payee", DbType="Int")]
		public System.Nullable<int> transaction_payee
		{
			get
			{
				return this._transaction_payee;
			}
			set
			{
				if ((this._transaction_payee != value))
				{
					this.Ontransaction_payeeChanging(value);
					this.SendPropertyChanging();
					this._transaction_payee = value;
					this.SendPropertyChanged("transaction_payee");
					this.Ontransaction_payeeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
