#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bookkeeping.App_Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="bookkeeping")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttransaction(transaction instance);
    partial void Updatetransaction(transaction instance);
    partial void Deletetransaction(transaction instance);
    partial void Insertparty(party instance);
    partial void Updateparty(party instance);
    partial void Deleteparty(party instance);
    partial void Insertorganization(organization instance);
    partial void Updateorganization(organization instance);
    partial void Deleteorganization(organization instance);
    #endregion
		
		public DataClassesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["bookkeepingConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<transaction> transactions
		{
			get
			{
				return this.GetTable<transaction>();
			}
		}
		
		public System.Data.Linq.Table<party> parties
		{
			get
			{
				return this.GetTable<party>();
			}
		}
		
		public System.Data.Linq.Table<organization> organizations
		{
			get
			{
				return this.GetTable<organization>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[transaction]")]
	public partial class transaction : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _transaction_id;
		
		private string _transaction_name;
		
		private string _transaction_description;
		
		private decimal _transaction_amount;
		
		private System.Nullable<int> _transaction_payer_id;
		
		private System.Nullable<int> _transaction_payee_id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ontransaction_idChanging(int value);
    partial void Ontransaction_idChanged();
    partial void Ontransaction_nameChanging(string value);
    partial void Ontransaction_nameChanged();
    partial void Ontransaction_descriptionChanging(string value);
    partial void Ontransaction_descriptionChanged();
    partial void Ontransaction_amountChanging(decimal value);
    partial void Ontransaction_amountChanged();
    partial void Ontransaction_payer_idChanging(System.Nullable<int> value);
    partial void Ontransaction_payer_idChanged();
    partial void Ontransaction_payee_idChanging(System.Nullable<int> value);
    partial void Ontransaction_payee_idChanged();
    #endregion
		
		public transaction()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_transaction_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int transaction_id
		{
			get
			{
				return this._transaction_id;
			}
			set
			{
				if ((this._transaction_id != value))
				{
					this.Ontransaction_idChanging(value);
					this.SendPropertyChanging();
					this._transaction_id = value;
					this.SendPropertyChanged("transaction_id");
					this.Ontransaction_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_transaction_name", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string transaction_name
		{
			get
			{
				return this._transaction_name;
			}
			set
			{
				if ((this._transaction_name != value))
				{
					this.Ontransaction_nameChanging(value);
					this.SendPropertyChanging();
					this._transaction_name = value;
					this.SendPropertyChanged("transaction_name");
					this.Ontransaction_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_transaction_description", DbType="VarChar(5000)")]
		public string transaction_description
		{
			get
			{
				return this._transaction_description;
			}
			set
			{
				if ((this._transaction_description != value))
				{
					this.Ontransaction_descriptionChanging(value);
					this.SendPropertyChanging();
					this._transaction_description = value;
					this.SendPropertyChanged("transaction_description");
					this.Ontransaction_descriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_transaction_amount", DbType="Money NOT NULL")]
		public decimal transaction_amount
		{
			get
			{
				return this._transaction_amount;
			}
			set
			{
				if ((this._transaction_amount != value))
				{
					this.Ontransaction_amountChanging(value);
					this.SendPropertyChanging();
					this._transaction_amount = value;
					this.SendPropertyChanged("transaction_amount");
					this.Ontransaction_amountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_transaction_payer_id", DbType="Int")]
		public System.Nullable<int> transaction_payer_id
		{
			get
			{
				return this._transaction_payer_id;
			}
			set
			{
				if ((this._transaction_payer_id != value))
				{
					this.Ontransaction_payer_idChanging(value);
					this.SendPropertyChanging();
					this._transaction_payer_id = value;
					this.SendPropertyChanged("transaction_payer_id");
					this.Ontransaction_payer_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_transaction_payee_id", DbType="Int")]
		public System.Nullable<int> transaction_payee_id
		{
			get
			{
				return this._transaction_payee_id;
			}
			set
			{
				if ((this._transaction_payee_id != value))
				{
					this.Ontransaction_payee_idChanging(value);
					this.SendPropertyChanging();
					this._transaction_payee_id = value;
					this.SendPropertyChanged("transaction_payee_id");
					this.Ontransaction_payee_idChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.party")]
	public partial class party : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _party_id;
		
		private string _party_name;
		
		private string _party_description;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onparty_idChanging(int value);
    partial void Onparty_idChanged();
    partial void Onparty_nameChanging(string value);
    partial void Onparty_nameChanged();
    partial void Onparty_descriptionChanging(string value);
    partial void Onparty_descriptionChanged();
    #endregion
		
		public party()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_party_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int party_id
		{
			get
			{
				return this._party_id;
			}
			set
			{
				if ((this._party_id != value))
				{
					this.Onparty_idChanging(value);
					this.SendPropertyChanging();
					this._party_id = value;
					this.SendPropertyChanged("party_id");
					this.Onparty_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_party_name", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string party_name
		{
			get
			{
				return this._party_name;
			}
			set
			{
				if ((this._party_name != value))
				{
					this.Onparty_nameChanging(value);
					this.SendPropertyChanging();
					this._party_name = value;
					this.SendPropertyChanged("party_name");
					this.Onparty_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_party_description", DbType="VarChar(5000)")]
		public string party_description
		{
			get
			{
				return this._party_description;
			}
			set
			{
				if ((this._party_description != value))
				{
					this.Onparty_descriptionChanging(value);
					this.SendPropertyChanging();
					this._party_description = value;
					this.SendPropertyChanged("party_description");
					this.Onparty_descriptionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.organization")]
	public partial class organization : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _organization_id;
		
		private string _organization_name;
		
		private string _organization_description;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onorganization_idChanging(int value);
    partial void Onorganization_idChanged();
    partial void Onorganization_nameChanging(string value);
    partial void Onorganization_nameChanged();
    partial void Onorganization_descriptionChanging(string value);
    partial void Onorganization_descriptionChanged();
    #endregion
		
		public organization()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_organization_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int organization_id
		{
			get
			{
				return this._organization_id;
			}
			set
			{
				if ((this._organization_id != value))
				{
					this.Onorganization_idChanging(value);
					this.SendPropertyChanging();
					this._organization_id = value;
					this.SendPropertyChanged("organization_id");
					this.Onorganization_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_organization_name", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string organization_name
		{
			get
			{
				return this._organization_name;
			}
			set
			{
				if ((this._organization_name != value))
				{
					this.Onorganization_nameChanging(value);
					this.SendPropertyChanging();
					this._organization_name = value;
					this.SendPropertyChanged("organization_name");
					this.Onorganization_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_organization_description", DbType="VarChar(5000)")]
		public string organization_description
		{
			get
			{
				return this._organization_description;
			}
			set
			{
				if ((this._organization_description != value))
				{
					this.Onorganization_descriptionChanging(value);
					this.SendPropertyChanging();
					this._organization_description = value;
					this.SendPropertyChanged("organization_description");
					this.Onorganization_descriptionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
